[package]
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]
name = "vimdecrypt"
version = "0.1.0"

[dependencies]
blowfish = "0.3.0"
clap = "2.31.2"
failure = "0.1.1"
generic-array = "0.9.0"
rpassword = "2.0.0"
sha2 = "0.7.1"
